GitHub ci
jrsteensen/OpenHornet-Software pull request #12
Opened 2023-10-16 16:07 UTC by calvinmorrow

## Description

Implement a distribute `make` build system that compiles all firmware in CI and (optionally) packages up the firmware into a release artifact which can be installed using avrdude or a GUI tool like [AVRDudess](https://blog.zakkemble.net/avrdudess-a-gui-for-avrdude/)
Addresses # (issue)

### Dependencies
* Implements several submodules that are included in the `/libraries` subfolder
* The Github Actions side is all self-contained.  The workflow should work properly on Linux and Mac, however the required setup and toolchain has not yet been documented for Windows.

### Type of change
- [ ] New software module (new software module for slave)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update outside of the automatically-generated doxygen documentation.

### Checklist:
- [X] My code follows the (style guidelines)[https://jrsteensen.github.io/OpenHornet-Software/d4/d46/md__2github_2workspace_2_s_t_y_l_e_g_u_i_d_e.html] of this project
- [X] (I have complied with the software manual)[https://jrsteensen.github.io/OpenHornet-Software/d7/d78/md__software_manual.html] for this project
- [X] I have performed a self-review of my own code
- [ ] I have commented my code fully with Doxygen compatible comments, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to non-Doxygen generated documentation
- [X] My changes generate no errors on compile in Arduino IDE
- [ ] My changes generate no new warnings on compile in Arduino IDE
- [ ] Any dependent changes have been merged and published in downstream modules

### How Has This Been Tested?
Github Actions workflows were tested in my [forked repository](https://github.com/calvinmorrow/OpenHornet-software/tree/github-ci)

A separate branch was created with some test sketches to verify workflow process and also [test artifacts](https://github.com/calvinmorrow/OpenHornet-Software/actions/runs/6535758295)
 
- [ ] I have tested the sketch in-circuit in DCS with DCS-BIOS and outputs (displays, LEDs, etc.) function as expected. 
- [ ] I have tested the sketch in-circuit in DCS with DCS-BIOS and HID inputs (switchs, pots, etc.) function as expected, with switches moving the correct direction.
- [ ] I have tested the sketch in-circuit in DCS with DCS-BIOS and any logic in the sketch has been tested and functions as expected.
- [ ] This code has not yet been tested in-circuit.
- [ ] This code has not yet been tested in DCS-BIOS.

#### Test Configuration
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

2023-10-16 23:35 UTC, jrsteensen requested changes
Looks absolutely fantastic! Just a few quick additions requested, but this is going to make things so much easier to validate moving forward. Thank you.

2023-10-16 23:35 UTC, jrsteensen commented on docs/SoftwareManual.md
> +`BOARD_TAG` should be set to the target Arduino board family.  Example options are `promicro`, `mega`, etc.  Run `make show_boards` to see a full list of valid board families.
Please list all choices for all the currently used microcontrollers for quick & easy reference.

2023-10-16 23:35 UTC, jrsteensen commented on docs/SoftwareManual.md
> +`BOARD_SUB` should be set to the specific sub-target of the board family.  Example options are `16MHzatmega32U4` (ProMicro 16MHz), `atmega2560` (Mega 2560), etc.  Run `make show_submenu` to see a ful
Please list all choices for all the currently used microcontrollers for quick & easy reference.

2023-10-16 23:35 UTC, jrsteensen commented on embedded/templates/OHSketchTemplate/Makefile
> +BOARD_TAG  = promicro
Add commented list of the other OH required microcontroller options for `BOARD_TAG` and `BOARD_SUB` fields.

2023-10-16 23:35 UTC, jrsteensen commented on include/promicro.mk
Do we need another one of these for every microcontroller?

2023-10-17 00:44 UTC, calvinmorrow commented on include/promicro.mk
Possibly.  The Pro Micro requires several variables set so I used the include to avoid duplicating those settings in each Makefile. .. although we could also set the BOARD_TAG and BOARD_SUB in a microcontroller specific include so that the sketch Makefile really only includes another file.

That might be a "friendlier" option than the BOARD_TAG/SUB vars.  Thoughts?

Simplest example:
```
BOARD_TAG = mega
BOARD_SUB = atmega2560
```

vs
```
include ../../include/mega2560.mk
```

2023-10-17 00:47 UTC, jrsteensen commented on include/promicro.mk
I like that idea, that way we have a "standard" makefile for each required microcontroller and it is a few less things to review that way. (If I'm understanding that we would use makefiles to specify which micro this uses, versus additional multiple variables.)

2023-10-17 01:04 UTC, jrsteensen commented on include/promicro.mk
If I recall off the top of my head, we use the following microcontrollers:

1. [Sparkfun Pro-Micro 5V](https://www.sparkfun.com/products/12640)
2. [Sparkfun Pro-Micro 3.3V](https://www.sparkfun.com/products/12587)
3. [Arduino Pro-Mini](https://www.sparkfun.com/products/11114)
4. [Arduino Mega 2560](https://store-usa.arduino.cc/products/arduino-mega-2560-rev3?selectedStore=us)
5. [Wemos S2 Mini](https://www.wemos.cc/en/latest/s2/s2_mini.html)

2023-10-17 01:44 UTC, kbastronomics commented on include/promicro.mk
I don't recall the Pro-Micro 3.3V being used anywhere.
Pro-Mini is 5V per the Inner Throttle Grip Schematic

2023-10-17 02:33 UTC, jrsteensen commented on include/promicro.mk
> I don't recall the Pro-Micro 3.3V being used anywhere. Pro-Mini is 5V per the Inner Throttle Grip Schematic

1. Pro-Mini is 3.3V since the S2 Mini is 3.3V and we don't have a level shifter on the controller.
2. I concur on the Pro-Micro 3.3V and removed it from the comment.

2023-10-18 03:10 UTC, calvinmorrow commented on docs/SoftwareManual.md
> +`BOARD_TAG` should be set to the target Arduino board family.  Example options are `promicro`, `mega`, etc.  Run `make show_boards` to see a full list of valid board families.
No longer necessary using the board-specific Makefile includes

2023-10-18 03:10 UTC, calvinmorrow commented on embedded/templates/OHSketchTemplate/Makefile
> +BOARD_TAG  = promicro
BOARD_TAG and BOARD_SUB now used only in board specific includes.

Added a list of all possible Makefile includes

2023-10-18 03:11 UTC, calvinmorrow commented on include/promicro.mk
I believe I have this setup now and poilshed a bit more as well as working with the S2 Mini.

Ready for re-review

2023-10-18 23:54 UTC, jrsteensen approved these changes
Approved As-Is. This will be fantastic!

2023-10-18 23:56 UTC, merged